require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe AcceptorsController do

  # This should return the minimal set of attributes required to create a valid
  # Acceptor. As you add validations to Acceptor, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end

  describe "GET index" do
    it "assigns all acceptors as @acceptors" do
      acceptor = Acceptor.create! valid_attributes
      get :index
      assigns(:acceptors).should eq([acceptor])
    end
  end

  describe "GET show" do
    it "assigns the requested acceptor as @acceptor" do
      acceptor = Acceptor.create! valid_attributes
      get :show, :id => acceptor.id.to_s
      assigns(:acceptor).should eq(acceptor)
    end
  end

  describe "GET new" do
    it "assigns a new acceptor as @acceptor" do
      get :new
      assigns(:acceptor).should be_a_new(Acceptor)
    end
  end

  describe "GET edit" do
    it "assigns the requested acceptor as @acceptor" do
      acceptor = Acceptor.create! valid_attributes
      get :edit, :id => acceptor.id.to_s
      assigns(:acceptor).should eq(acceptor)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Acceptor" do
        expect {
          post :create, :acceptor => valid_attributes
        }.to change(Acceptor, :count).by(1)
      end

      it "assigns a newly created acceptor as @acceptor" do
        post :create, :acceptor => valid_attributes
        assigns(:acceptor).should be_a(Acceptor)
        assigns(:acceptor).should be_persisted
      end

      it "redirects to the created acceptor" do
        post :create, :acceptor => valid_attributes
        response.should redirect_to(Acceptor.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved acceptor as @acceptor" do
        # Trigger the behavior that occurs when invalid params are submitted
        Acceptor.any_instance.stub(:save).and_return(false)
        post :create, :acceptor => {}
        assigns(:acceptor).should be_a_new(Acceptor)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Acceptor.any_instance.stub(:save).and_return(false)
        post :create, :acceptor => {}
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested acceptor" do
        acceptor = Acceptor.create! valid_attributes
        # Assuming there are no other acceptors in the database, this
        # specifies that the Acceptor created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Acceptor.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, :id => acceptor.id, :acceptor => {'these' => 'params'}
      end

      it "assigns the requested acceptor as @acceptor" do
        acceptor = Acceptor.create! valid_attributes
        put :update, :id => acceptor.id, :acceptor => valid_attributes
        assigns(:acceptor).should eq(acceptor)
      end

      it "redirects to the acceptor" do
        acceptor = Acceptor.create! valid_attributes
        put :update, :id => acceptor.id, :acceptor => valid_attributes
        response.should redirect_to(acceptor)
      end
    end

    describe "with invalid params" do
      it "assigns the acceptor as @acceptor" do
        acceptor = Acceptor.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Acceptor.any_instance.stub(:save).and_return(false)
        put :update, :id => acceptor.id.to_s, :acceptor => {}
        assigns(:acceptor).should eq(acceptor)
      end

      it "re-renders the 'edit' template" do
        acceptor = Acceptor.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Acceptor.any_instance.stub(:save).and_return(false)
        put :update, :id => acceptor.id.to_s, :acceptor => {}
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested acceptor" do
      acceptor = Acceptor.create! valid_attributes
      expect {
        delete :destroy, :id => acceptor.id.to_s
      }.to change(Acceptor, :count).by(-1)
    end

    it "redirects to the acceptors list" do
      acceptor = Acceptor.create! valid_attributes
      delete :destroy, :id => acceptor.id.to_s
      response.should redirect_to(acceptors_url)
    end
  end

end
